# Generated by Django 3.2.16 on 2023-07-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mseed',
            name='traces',
            field=models.TextField(blank=True),
        ),
    ]
